import {useEffect,useRef,useState} from 'react';
import {motion} from 'framer-motion';
import {Check,Flame,Hand,Play,Rocket,Star} from 'lucide-react';
import type {Topic} from '../types';
import {PlanetBadge} from './Planet';
import {voice} from '../audio';
const order=['mercury','venus','earth','mars','jupiter','saturn','uranus','neptune'];
const names=['Mercúrio','Vênus','Terra','Marte','Júpiter','Saturno','Urano','Netuno'];
const emojis:Record<string,string>={count:'⭐',moons:'🌘',craters:'◉',wind:'☁️',tilt:'🔵'};
const shuffledNumbers=[3,7,1,9,5,2,10,4,8,6];
export default function Activities({topic,onWin,reduced}:{topic:Topic;onWin:()=>void;reduced:boolean}){
 const [step,setStep]=useState(0),[picked,setPicked]=useState<number[]>([]),[hint,setHint]=useState(false),[round,setRound]=useState(0),[drawing,setDrawing]=useState(false),[path,setPath]=useState<{x:number;y:number}[]>([]),[launched,setLaunched]=useState(false);
 const canvas=useRef<SVGSVGElement>(null);const game=topic.game;const total=game==='numbers'?10:game==='order'?8:game==='dress'?4:game==='rocket'?3:game==='rings'?3:game==='moons'?2:game==='jump'?3:game==='sum'?[2,3,5][round]:game==='shapes'?3:game==='draw'?1:['hot','race','biggest'].includes(game)?1:5;
 const done=step>=total;const allDone=done&&!(game==='sum'&&round<2)&&!(game==='numbers'&&round===0)&&!(game==='dress'&&round===0);
 useEffect(()=>{void voice.play(game==='sum'?'sum-0':game)},[game]);
 const correct=(index?:number)=>{if(done)return;if(index!==undefined&&picked.includes(index))return;if(index!==undefined)setPicked(p=>[...p,index]);setStep(s=>s+1);setHint(false);voice.chime();void voice.play(['count','craters','moons','numbers'].includes(game)?`number-${step+1}`:'good')};
 const wrong=()=>{setHint(true);void voice.play('try')};
 const acceptDrop=(e:React.DragEvent,expected:string,action:()=>void)=>{e.preventDefault();if(e.dataTransfer.getData('text/plain')===expected)action();else wrong()};
 const nextRound=()=>{setRound(r=>r+1);setStep(0);setPicked([]);setHint(false);void voice.play(game==='sum'?`sum-${round+1}`:game==='numbers'?'missing':'pack')};
 const actionButton=(text:string,action:()=>void)=><button className="primary activity-action" onClick={action}><Play size={26} fill="currentColor"/>{text}</button>;
 const advance=()=>{if(game==='rocket')setLaunched(true);onWin()};
 let content:React.ReactNode;
 if(['count','moons','craters'].includes(game))content=<div className={`count-field ${game==='craters'?'crater-field':''}`}>{Array.from({length:total},(_,i)=><motion.button key={i} aria-label={`Contar ${i+1}`} className={`collect-object ${picked.includes(i)?'collected':''}`} onClick={()=>correct(i)}  disabled={picked.includes(i)}>{picked.includes(i)?<><Check/ ><b>{picked.indexOf(i)+1}</b></>:emojis[game]}</motion.button>)}</div>;
 else if(['hot','biggest','race'].includes(game)){const opts=game==='hot'?[['sun','Quentinho'],['neptune','Geladinho']]:game==='biggest'?[['earth','Terra'],['jupiter','Júpiter'],['mars','Marte']]:[['🐢','Tartaruga'],['🚀','Foguete'],['✨','Luz']];const answer=game==='hot'?0:game==='biggest'?1:2;content=<><div className="answer-options">{opts.map(([id,name],i)=><button key={id} disabled={done} className={`answer ${hint&&i===answer?'hint':''} ${done&&i===answer?'chosen':''}`} onClick={()=>i===answer?correct():wrong()}>{game==='race'?<span className="race-emoji">{id}</span>:<PlanetBadge id={id} size={id==='jupiter'?104:76}/>}<b>{name}</b></button>)}</div>{done&&game==='race'&&<div className="race-tracks">{['🐢','🚀','✨'].map((x,i)=><motion.div key={x} initial={{x:0}} animate={{x:'80%'}} transition={{duration:reduced?.01:[8,3,.4][i]}}>{x}</motion.div>)}</div>}</>}
 else if(game==='jump')content=<><div className="jump-worlds">{['earth','moon'].map((id,i)=><div className="jump-world" key={id}><motion.img key={`${id}-${step}`} src={`${import.meta.env.BASE_URL}art/tomas.webp`} alt="Tomás pulando" animate={step&&!reduced?{y:[0,i?-100:-35,0]}:{}} transition={{duration:1.2}}/><PlanetBadge id={id} size={100}/><b>{i?'Na Lua':'Na Terra'}</b></div>)}</div>{actionButton('Vamos pular!',()=>correct())}</>;
 else if(game==='order')content=<><div className="order-slots"><span className="order-sun">☀</span>{order.map((id,i)=><button key={id} className={`orbit-slot ${i===step?'current':''}`} aria-label={`Órbita ${i+1}`} onDragOver={e=>e.preventDefault()} onDrop={e=>acceptDrop(e,order[step],()=>correct())} onClick={()=>{if(i===step)void voice.play(`${id}-intro`)}}>{i<step?<PlanetBadge id={id} size={45}/>:i+1}</button>)}</div><div className="planet-picks">{[4,0,6,2,7,1,5,3].map(i=><button key={i} disabled={i<step} draggable={i>=step} onDragStart={e=>e.dataTransfer.setData('text/plain',order[i])} className={`answer ${hint&&i===step?'hint':''}`} onClick={()=>i===step?correct():wrong()} aria-label={`Colocar ${names[i]}`}><PlanetBadge id={order[i]} size={52}/><b>{names[i]}</b></button>)}</div></>;
 else if(game==='numbers'&&round===0)content=<div className="number-grid">{shuffledNumbers.map(n=><button key={n} disabled={picked.includes(n)} className={`number-tile ${picked.includes(n)?'chosen':''} ${hint&&n===step+1?'hint':''}`} onClick={()=>n===step+1?correct(n):wrong()}>{n}</button>)}</div>;
 else if(game==='numbers')content=<><div className="sequence">1 · 2 · <span>?</span> · 4</div><div className="answer-options">{[5,3,8].map(n=><button className={`number-tile ${hint&&n===3?'hint':''}`} key={n} onClick={()=>{if(n===3){setStep(10);voice.chime();void voice.play('good')}else wrong()}}>{n}</button>)}</div></>;
 else if(game==='sum')content=<><div className="sum-equation"><span>{'☄️'.repeat([1,2,3][round])}</span><b>+</b><span>{'☄️'.repeat([1,1,2][round])}</span></div><div className="stone-tray">{Array.from({length:5},(_,i)=><button className={`stone ${picked.includes(i)?'packed':''}`} key={i} draggable={!picked.includes(i)} onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} disabled={picked.includes(i)||done} onClick={()=>correct(i)}>☄️</button>)}</div><div className="basket" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(id)&&id>=0&&id<5)correct(id)}}><span>▱</span><b>{step} / {total}</b></div></>;
 else if(game==='rings')content=<><div className="ring-assembly" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const i=Number(e.dataTransfer.getData('text/plain'));if(i>=0&&i<3)correct(i)}}><PlanetBadge id="saturn" size={140}/>{Array.from({length:step},(_,i)=><i key={i} className="assembled-ring" style={{width:190+i*30,height:55+i*20}}/>)}</div><div className="answer-options">{[0,1,2].map(i=><button aria-label={`Adicionar anel ${i+1}`} className={`answer ring-token ${picked.includes(i)?'chosen':''}`} key={i} disabled={picked.includes(i)} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onClick={()=>correct(i)}><span>◯</span></button>)}</div></>;
 else if(game==='rocket'||(game==='dress'&&round===0)){const icons=game==='rocket'?['🔥','🛢️','🚀']:['👕','🥾','🧤','🪖'];const labels=game==='rocket'?['Motor','Tanque','Cápsula']:['Traje','Botas','Luvas','Capacete'];content=<><div className={`build-zone ${launched?'launching':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>acceptDrop(e,String(step),()=>correct())}><span className="build-outline">{game==='rocket'?<Rocket size={90}/>:<img src={`${import.meta.env.BASE_URL}art/tomas.webp`} alt="Tomás"/>}</span><div className="build-pieces">{icons.slice(0,step).map((x,i)=><span key={i}>{x}</span>)}</div><small>{step} / {icons.length}</small></div><div className="answer-options">{icons.map((x,i)=><button key={i} className={`answer ${hint&&i===step?'hint':''} ${i<step?'chosen':''}`} draggable={i>=step} onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} disabled={i<step} onClick={()=>i===step?correct():wrong()}><span className="build-emoji">{x}</span><b>{labels[i]}</b></button>)}</div></>}
 else if(game==='dress')content=<><div className="answer-options">{['🍎','🥛','🥪','💧'].map((x,i)=><button key={i} className={`answer ${picked.includes(i)?'chosen':''}`} disabled={picked.includes(i)} onClick={()=>correct(i)}><span className="build-emoji">{x}</span></button>)}</div><div className="basket">🎒 {step} / 4</div></>;
 else if(game==='shapes'){const targets=['●','★','🌀'];const opts=[['★','●','▲'],['●','▲','★'],['🌀','★','●']][step]||[];content=<><div className="shape-model">{targets[step]||'✓'}</div><div className="answer-options">{opts.map((x,i)=><button key={`${step}-${i}`} className={`answer shape-choice ${hint&&x===targets[step]?'hint':''}`} onClick={()=>x===targets[step]?correct():wrong()}>{x}</button>)}</div></>}
 else if(game==='draw'){const point=(e:React.PointerEvent)=>{const rect=canvas.current!.getBoundingClientRect();return{x:(e.clientX-rect.left)/rect.width*600,y:(e.clientY-rect.top)/rect.height*270}};content=<><svg className="drawing-board" viewBox="0 0 600 270" ref={canvas} aria-label="Desenhe uma espiral" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDrawing(true);setPath(p=>[...p,point(e)])}} onPointerMove={e=>{if(drawing)setPath(p=>[...p,point(e)])}} onPointerUp={()=>setDrawing(false)} onPointerCancel={()=>setDrawing(false)}><path d="M300 140 C330 150 335 100 300 100 C220 80 235 200 320 190 C450 180 440 25 300 35 C125 30 100 245 325 245" fill="none" stroke="#b79afa" strokeWidth="3" strokeDasharray="7 10"/><polyline points={path.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#fadb90" strokeWidth="5" strokeLinecap="round"/>{path.filter((_,i)=>i%6===0).map((p,i)=><text key={i} x={p.x} y={p.y} fill="#fff3ab" fontSize="18">✦</text>)}</svg>{actionButton('Minha galáxia!',()=>{if(path.length>5)correct();else{setHint(true);void voice.play('draw')}})}</>}
 else if(game==='boost')content=<><div className="safe-route"><PlanetBadge id="blackhole" size={108}/><motion.div animate={{x:step*26}} transition={{duration:reduced?0:.4}}><Rocket size={65}/></motion.div><span className="safe-star">✦</span></div>{actionButton('Ligar o motor',()=>correct())}<p className="small-note">Nossa nave segue longe, numa rota segura.</p></>;
 else if(game==='tilt')content=<><motion.div className="tilting-world" animate={{rotate:step*19.6}} transition={{duration:reduced?0:.5}}><PlanetBadge id="uranus" size={145}/><div className="axis"/></motion.div>{actionButton('Girar de ladinho',()=>correct())}</>;
 else content=<><div className="wind-world"><PlanetBadge id="neptune" size={150}/>{[0,1,2].map(i=><motion.span key={`${i}-${step}`} initial={{x:-80,y:i*35}} animate={{x:step?90:-40}} transition={{duration:reduced?0:1.2+i*.4}}>☁️</motion.span>)}</div>{actionButton('Soprar os ventos',()=>correct())}</>;
 return <section className="activity"><div className="activity-top"><span className="eyebrow"><Hand size={15}/> Agora é com você!</span><span className="task-count">{Math.min(step,total)} / {total}</span></div><h2>{hint?'Vamos tentar juntos!':voice.text(game==='sum'?`sum-${round}`:game==='numbers'&&round?'missing':game==='dress'&&round?'pack':game)}</h2><div className="activity-body">{content}</div><div className="step-dots">{Array.from({length:total},(_,i)=><span key={i} className={i<step?'filled':''}/>)}</div>{done&&<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="activity-finish"><div><Star fill="#fbc55e" color="#fbc55e"/> Muito bem, Tomás!</div>{allDone?<button className="primary" onClick={advance}><Check/>Ganhar figurinha</button>:<button className="primary" onClick={nextRound}><Play fill="currentColor"/>Mais uma brincadeira</button>}</motion.div>}</section>
}
