import { useEffect,useRef,useState } from 'react';
import * as THREE from 'three';
import { Rocket,Orbit,Sparkles } from 'lucide-react';
const colors:Record<string,string>={earth:'#389fd1',sun:'#ffbc48',mercury:'#aaa598',venus:'#e2ad6d',mars:'#e37450',jupiter:'#ddb792',saturn:'#e7ca98',uranus:'#9bd9dc',neptune:'#537be0',moon:'#c7cdd5',blackhole:'#080a12',galaxy:'#b691e7',comets:'#7ee3ed',rockets:'#9de9d3',astronaut:'#f1b7c4',numbers:'#f9d46c',shapes:'#b497f1',light:'#ffe87e',order:'#b9dfe8'};
export function PlanetBadge({id,size=64}:{id:string;size?:number}){
 const special:Record<string,string>={rockets:'🚀',astronaut:'🧑‍🚀',numbers:'123',shapes:'✦',light:'✧',galaxy:'✺',comets:'☄',blackhole:'',order:''};
 return <span aria-hidden="true" className={`planet-badge p-${id}`} style={{width:size,height:size,'--planet':colors[id]||'#9edcd9'} as React.CSSProperties}>{id in special?<span className="special-planet">{special[id]||<Orbit size={size*.65}/>}</span>:<><span className="planet-grain"/>{['saturn','uranus'].includes(id)&&<i className="mini-ring"/>}<span className="tiny-face">⌣</span></>}</span>
}
function texture(id:string){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d')!;x.fillStyle=colors[id]||'#8866bb';x.fillRect(0,0,1024,512);let seed=42;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
 for(let i=0;i<18000;i++){const px=random()*1024,py=random()*512;x.fillStyle=`rgba(${id==='sun'?'255,217,120':'255,255,255'},${random()*.09})`;x.fillRect(px,py,random()*4+1,2)}
 if(id==='earth'){x.fillStyle='#67c39c';for(let i=0;i<11;i++){const cx=random()*1024,cy=80+random()*370,r=30+random()*80;x.beginPath();for(let j=0;j<26;j++){const a=j/26*Math.PI*2,rr=r*(.5+random()*.5);const px=cx+Math.cos(a)*rr,py=cy+Math.sin(a)*rr*.68;j?x.lineTo(px,py):x.moveTo(px,py)}x.closePath();x.fill()}x.fillStyle='#e5faff';x.fillRect(0,0,1024,22);x.fillRect(0,493,1024,19);for(let i=0;i<35;i++){x.fillStyle='#ffffff99';x.beginPath();x.ellipse(random()*1024,random()*512,35+random()*40,4+random()*9,-.15,0,Math.PI*2);x.fill()}}
 if(['jupiter','saturn','venus','neptune','uranus'].includes(id)){for(let i=0;i<45;i++){x.fillStyle=i%2?`rgba(255,246,220,${random()*.25})`:`rgba(95,53,55,${random()*.18})`;x.fillRect(0,i*13+random()*5,1024,3+random()*14)}if(id==='jupiter'){x.fillStyle='#ad7459';x.beginPath();x.ellipse(760,320,80,33,0,0,Math.PI*2);x.fill()}}
 if(['mercury','moon','mars'].includes(id)){for(let i=0;i<90;i++){const cx=random()*1024,cy=random()*512,r=3+random()*16;x.fillStyle='#201a2022';x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.fill();x.strokeStyle='#ffffff25';x.lineWidth=2;x.stroke()}}
 const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
export function PlanetScene({id,reduced=false}:{id:string;reduced?:boolean}){
 const host=useRef<HTMLDivElement>(null);const [fallback,setFallback]=useState(false);
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'})}catch{setFallback(true);return}
 setFallback(false);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));el.appendChild(renderer.domElement);const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(0,0,5.5);scene.add(new THREE.AmbientLight('#becaff',2));const light=new THREE.DirectionalLight('#fff3da',4);light.position.set(-3,4,5);scene.add(light);const group=new THREE.Group();scene.add(group);const geometries:THREE.BufferGeometry[]=[];const materials:THREE.Material[]=[];const textures:THREE.Texture[]=[];
 const special=['rockets','astronaut','numbers','shapes','light','order','comets'].includes(id);const planetId=special?(id==='light'?'sun':'earth'):id;
 const tex=texture(planetId);textures.push(tex);const geo=new THREE.SphereGeometry(id==='blackhole'?.73:1.15,64,40);const mat=new THREE.MeshStandardMaterial({map:tex,roughness:.85,metalness:.02,emissive:planetId==='sun'?'#ff9300':planetId==='blackhole'?'#000000':'#000000',emissiveIntensity:planetId==='sun'?.5:0});geometries.push(geo);materials.push(mat);const sphere=new THREE.Mesh(geo,mat);group.add(sphere);sphere.rotation.z=planetId==='uranus'?1.65:.16;
 if(['saturn','uranus','blackhole','galaxy','order'].includes(id)){for(let i=0;i<(id==='blackhole'?6:3);i++){const rg=new THREE.RingGeometry(1.4+i*.065,1.45+i*.065,96);const rm=new THREE.MeshBasicMaterial({color:id==='blackhole'?['#fff2c9','#ffbd73','#e78d61'][i%3]:id==='galaxy'?'#cdb1ff':'#d1bea0',transparent:true,opacity:.7-i*.05,side:THREE.DoubleSide});const ring=new THREE.Mesh(rg,rm);ring.rotation.x=1.18;ring.rotation.y=.16;group.add(ring);geometries.push(rg);materials.push(rm)}}
 if(id==='earth'){const g=new THREE.SphereGeometry(.21,24,16),t=texture('moon'),m=new THREE.MeshStandardMaterial({map:t});const moon=new THREE.Mesh(g,m);moon.position.set(1.55,.65,.2);group.add(moon);geometries.push(g);materials.push(m);textures.push(t)}
 const pts=new Float32Array(120*3);for(let i=0;i<pts.length;i++)pts[i]=(Math.random()-.5)*12;const starsG=new THREE.BufferGeometry();starsG.setAttribute('position',new THREE.BufferAttribute(pts,3));const starsM=new THREE.PointsMaterial({color:'#c1d8ff',size:.018,transparent:true,opacity:.6});scene.add(new THREE.Points(starsG,starsM));geometries.push(starsG);materials.push(starsM);
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera)};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0;let dragging=false,lastX=0;const down=(e:PointerEvent)=>{dragging=true;lastX=e.clientX;el.setPointerCapture(e.pointerId)};const move=(e:PointerEvent)=>{if(dragging){group.rotation.y+=(e.clientX-lastX)*.012;lastX=e.clientX;if(reduced)renderer.render(scene,camera)}};const up=()=>dragging=false;el.addEventListener('pointerdown',down);el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);
 let previous=0;const animate=(time:number)=>{if(!reduced)frame=requestAnimationFrame(animate);if(!reduced&&time-previous<16)return;previous=time;if(!reduced&&!dragging){sphere.rotation.y+=.003;group.position.y=Math.sin(time*.0007)*.055}renderer.render(scene,camera)};frame=requestAnimationFrame(animate);
 return()=>{cancelAnimationFrame(frame);observer.disconnect();el.removeEventListener('pointerdown',down);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()};
 },[id,reduced]);
 return <div className="planet-scene" ref={host} role="img" aria-label={`Modelo ilustrado de ${id}. Arraste para girar.`}>{fallback&&<PlanetBadge id={id} size={230}/>} {['rockets','astronaut'].includes(id)&&<div className="scene-symbol">{id==='rockets'?<Rocket size={120}/>:<Sparkles size={100}/>}</div>}</div>
}
