import {useEffect,useMemo,useState} from 'react';
import {AnimatePresence,motion,MotionConfig} from 'framer-motion';
import {ArrowLeft,BookOpen,Check,ChevronLeft,ChevronRight,Compass,Headphones,Heart,Lock,Map,Music2,Pause,Play,Repeat2,Rocket,Settings2,ShieldCheck,Sparkles,Star,Trophy,Volume2,VolumeX,X} from 'lucide-react';
import content from './content.json';
import type {Page,Settings,Topic} from './types';
import {voice} from './audio';
import {PlanetBadge,PlanetScene} from './components/Planet';
import Activities from './components/Activities';
const topics=content as Topic[];
const planetIds=['mercury','venus','earth','mars','jupiter','saturn','uranus','neptune'];
const categories=[['todos','Todos os mundos'],['planetas','Planetas'],['universo','Universo'],['aventuras','Astronautas'],['brincadeiras','Brincadeiras']];
const initialSettings:Settings={muted:false,music:false,volume:.85,rate:1,reduced:window.matchMedia('(prefers-reduced-motion: reduce)').matches,suit:0};
function Buddy({text,playing=false}:{text:string;playing?:boolean}){return <div className="buddy"><div className={`star-buddy ${playing?'speaking':''}`}><span>✦</span><i>••</i><b>⌣</b></div><div><span className="buddy-name">ESTRELINHA <i/></span><p>{text}</p></div></div>}
function ChapterScene({topic,visual,reduced,suit}:{topic:Topic;visual:string;reduced:boolean;suit:number}){const [touch,setTouch]=useState(0);useEffect(()=>setTouch(0),[visual]);return <div className={`chapter-scene visual-${visual}`}><PlanetScene id={topic.id} reduced={reduced}/>{['orbit','order','ring'].includes(visual)&&<div className="orbit-illustration"><i/><i/><motion.span animate={!reduced?{rotate:360}:{}} transition={{duration:16,repeat:Infinity,ease:'linear'}}>✦</motion.span></div>}{['light','day','hot','cold'].includes(visual)&&<div className="sunlight-illustration"><span>☀</span><i/><i/><i/></div>}{['count','star','color','shape','spiral'].includes(visual)&&<div className="orbit-sparkles">✦ <span>✧</span> ✦</div>}{['thrust','build','rover'].includes(visual)&&<motion.div className="flying-rocket" animate={!reduced?{y:[10,-30,10]}:{}} transition={{duration:5,repeat:Infinity}}><Rocket size={95}/><span>🔥</span></motion.div>}{['jump','float','suit','food','safe'].includes(visual)&&<motion.img className={`floating-tomas suit-${suit}`} src={`${import.meta.env.BASE_URL}art/tomas.webp`} alt="Tomás astronauta" animate={!reduced?{y:[0,-25,0]}:{}} transition={{duration:4,repeat:Infinity}}/>}<button className="scene-touch" onClick={()=>{setTouch(x=>x+1);voice.chime()}} aria-label="Interagir com a cena"><Sparkles/>{touch?'Uau, que descoberta!':'Toque para descobrir'}</button><AnimatePresence>{touch>0&&<motion.div key={touch} className="scene-burst" initial={{scale:.1,opacity:1}} animate={{scale:3,opacity:0}} exit={{opacity:0}} transition={{duration:1.2}}>✦ ✧ ✦</motion.div>}</AnimatePresence><small>Ilustração para aprender · tamanhos fora de escala</small></div>}
export default function App(){
 const [page,setPage]=useState<Page>('explore'),[selected,setSelected]=useState('earth'),[filter,setFilter]=useState('todos'),[welcomed,setWelcomed]=useState(false),[settings,setSettings]=useState(initialSettings),[playing,setPlaying]=useState(false),[completed,setCompleted]=useState<string[]>([]),[allOpen,setAllOpen]=useState(false),[lesson,setLesson]=useState<Topic|null>(null),[fact,setFact]=useState(0),[mode,setMode]=useState<'learn'|'game'>('learn'),[mission,setMission]=useState<Topic|null>(null),[countdown,setCountdown]=useState<number|null>(null),[reward,setReward]=useState<Topic|null>(null),[parent,setParent]=useState(false),[gate,setGate]=useState(false),[resetConfirm,setResetConfirm]=useState(false),[notice,setNotice]=useState(''),[factOnly,setFactOnly]=useState(false);
 const topic=topics.find(t=>t.id===selected)!;
 const filtered=useMemo(()=>topics.filter(t=>filter==='todos'||t.category===filter),[filter]);
 const nextIndex=topics.findIndex(t=>!completed.includes(t.id));const nextMission=topics[nextIndex<0?0:nextIndex];
 useEffect(()=>{voice.onChange(setPlaying);return()=>{voice.stop();voice.music(false)}},[]);
 useEffect(()=>{voice.configure(settings.volume,settings.rate,settings.muted);voice.music(settings.music);document.documentElement.classList.toggle('reduce-motion',settings.reduced)},[settings]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{if(countdown===null)return;if(countdown===0){void voice.play('go');const timer=setTimeout(()=>{setCountdown(null);if(mission){setLesson(mission);setFact(0);setMode('learn');setMission(null)}},1000);return()=>clearTimeout(timer)}void voice.play(`number-${countdown}`);const timer=setTimeout(()=>setCountdown(n=>n===null?null:n-1),1150);return()=>clearTimeout(timer)},[countdown,mission]);
 useEffect(()=>{if(lesson&&mode==='learn')void voice.play(`${lesson.id}-${fact}`)},[lesson,fact,mode]);
 const navigate=(p:Page)=>{voice.stop();setPage(p);void voice.play(p);setFilter('todos')};
 const visit=(t:Topic,index=0,only=false)=>{setLesson(t);setMode('learn');setFact(index);setFactOnly(only)};
 const start=(t:Topic)=>{const idx=topics.indexOf(t);if(!allOpen&&idx>0&&!completed.includes(topics[idx-1].id)){setNotice('Mais uma descoberta e essa aventura se abre!');void voice.play('locked');return}setFactOnly(false);setMission(t);setCountdown(5);voice.music(settings.music)};
 const finish=()=>{if(!lesson)return;setCompleted(p=>p.includes(lesson.id)?p:[...p,lesson.id]);setReward(lesson);setLesson(null);voice.chime();void voice.play('reward')};
 const close=()=>{voice.stop();setLesson(null)};
 const stars=completed.length*3;
 return <MotionConfig reducedMotion={settings.reduced?'always':'never'}><div className="app-shell"><SuitFilters/><div className="background-stars" aria-hidden="true"/>
 <header className="topbar"><button className="brand" aria-label="Início" onClick={()=>navigate('explore')}><span className="brand-emblem"><Rocket size={27}/></span><span><b>TOMÁS</b><small>O ASTRONAUTA</small></span><span className="brand-dot">✦</span></button><nav className="main-nav" aria-label="Navegação principal">{([['explore','Explorar',Compass],['missions','Aventuras',Rocket],['discoveries','Descobertas',BookOpen],['album','Meu álbum',Star]] as const).map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}><Icon size={23}/><span>{label}</span>{page===id&&<motion.i layoutId="nav-dot"/>}</button>)}</nav><div className="top-actions"><span className="star-counter"><Star size={20} fill="#ffc96e"/>{stars}</span><button className={`icon-button ${playing?'audio-on':''}`} onClick={()=>voice.repeat()} aria-label="Ouvir de novo"><Volume2/></button><button className="icon-button parent-icon" onClick={()=>{setParent(true);setGate(false);voice.stop();void voice.play('gate')}} aria-label="Área da família"><Settings2/></button></div></header>
 <main>
 {page==='explore'&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="explore-page"><div className="page-heading"><div><span className="eyebrow"><span className="little-star">✦</span> Pequenas grandes descobertas</span><h1>O universo está esperando,<br/><em>comandante Tomás.</em></h1></div><div className="mission-status"><span className="status-orbit"><Rocket/></span><div><small>Seu diário de bordo</small><b>{completed.length} de {topics.length} aventuras</b><div className="progress-line"><i style={{width:`${completed.length/topics.length*100}%`}}/></div></div></div></div>
 <section className="observatory"><div className="orbital-grid"/><div className="observatory-copy"><span className="pill"><span/> Destino em vista</span><AnimatePresence mode="wait"><motion.div key={selected} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}}><h2>{topic.name}<span>✦</span></h2><p>{topic.tagline}</p><div className="destination-details"><span><Headphones size={17}/>5 descobertas para ouvir</span><span><HandIcon/> Uma brincadeira para explorar</span></div></motion.div></AnimatePresence><button className="primary" onClick={()=>visit(topic)}><Play size={25} fill="currentColor"/>Vamos conhecer!</button><span className="model-caption">Arraste o planeta para girar.</span></div><div className="observatory-globe"><PlanetScene id={selected} reduced={settings.reduced}/><span className="orbit-label"><i/> Olá, {topic.name}!</span></div><div className="tomas-companion"><div className="speech-tag">Vamos juntos?<span>✧</span></div><img className={`suit-${settings.suit}`} src={`${import.meta.env.BASE_URL}art/tomas.webp`} alt="Tomás sorrindo e acenando com traje de astronauta"/><span className="captain-badge"><Star size={14} fill="currentColor"/> Comandante Tomás</span></div></section>
 <div className="solar-rail"><div className="rail-heading"><span className="eyebrow">Uma estrela. Oito planetas.</span><span className="small-note">Toque e escolha seu destino</span></div><div className="planet-rail">{['sun',...planetIds].map((id,i)=>{const p=topics.find(t=>t.id===id)!;return <button key={id} className={`planet-stop ${selected===id?'selected':''}`} onClick={()=>{setSelected(id);void voice.play(`${id}-intro`)}}><PlanetBadge id={id} size={id==='sun'?58:48}/><b>{p.name}</b><span>{i?`${i}º planeta`:'Nossa estrela'}</span>{selected===id&&<i/>}</button>})}</div></div>
 <section className="beyond-row"><button className="feature-card card-rocket" onClick={()=>visit(topics.find(t=>t.id==='rockets')!)}><div className="feature-icon"><Rocket size={39}/></div><div><small>Oficina espacial</small><h3>Como um foguete voa?</h3><p>Monte, descubra e prepare a decolagem.</p></div><span className="feature-play"><Play size={24} fill="currentColor"/></span></button><button className="feature-card card-hole" onClick={()=>visit(topics.find(t=>t.id==='blackhole')!)}><div className="blackhole-icon"/><div><small>Mistérios do universo</small><h3>E os buracos negros?</h3><p>Uma viagem curiosa, do lado seguro.</p></div><span className="feature-play"><Play size={24} fill="currentColor"/></span></button></section><Buddy text="Cada pergunta é o começo de uma grande aventura." playing={playing}/>
 </motion.div>}
 {page==='missions'&&<div className="collection-page"><div className="page-heading"><div><span className="eyebrow">Seu mapa de aventuras</span><h1>Aprender brincando.<br/><em>Uma descoberta de cada vez.</em></h1></div><button className="primary" onClick={()=>start(nextMission)}><Play fill="currentColor"/>Continuar aventura</button></div><div className="missions-grid">{topics.map((t,i)=>{const unlocked=allOpen||i===0||completed.includes(topics[i-1].id),done=completed.includes(t.id);return <button className={`mission-card ${unlocked?'':'locked'} ${done?'complete':''}`} key={t.id} onClick={()=>start(t)}><span className="mission-number">{String(i+1).padStart(2,'0')}</span><div className="mission-art"><PlanetBadge id={t.id} size={95}/></div><span className="mission-category">{t.category==='planetas'?'Expedição planetária':t.category==='brincadeiras'?'Laboratório do Tomás':'Além dos planetas'}</span><h3>{t.name}</h3><p>{t.tagline}</p><div className="mission-bottom">{done?<span className="earned">★★★</span>:<span>2–4 min • no seu ritmo</span>}{unlocked?<Play size={21} fill="currentColor"/>:<Lock size={20}/>}</div></button>})}</div></div>}
 {page==='discoveries'&&<div className="collection-page"><div className="page-heading"><div><span className="eyebrow">Biblioteca de pequenas perguntas</span><h1>Tem tanta coisa<br/><em>para descobrir!</em></h1></div><div className="fact-total"><Sparkles/><b>95</b><span>curiosidades narradas</span></div></div><div className="filter-bar">{categories.map(([id,label])=><button className={filter===id?'selected':''} key={id} onClick={()=>{setFilter(id);void voice.play('discoveries')}}>{label}</button>)}</div><div className="discovery-grid">{filtered.map(t=><article className="discovery-card" key={t.id}><div className="discovery-top"><PlanetBadge id={t.id} size={67}/><div><h2>{t.name}</h2><small>{t.tagline}</small></div></div>{t.facts.map((f,i)=><button className="fact-row" key={f.title} onClick={()=>visit(t,i,true)}><span>{String(i+1).padStart(2,'0')}</span><b>{f.title}</b><Volume2 size={20}/></button>)}</article>)}</div></div>}
 {page==='album'&&<div className="collection-page"><div className="page-heading"><div><span className="eyebrow">Colecionando momentos de descoberta</span><h1>Meu álbum<br/><em>de astronauta.</em></h1></div><div className="fact-total"><Star fill="currentColor"/><b>{stars}</b><span>estrelas conquistadas</span></div></div><div className="album-banner"><Trophy size={43}/><div><h2>{completed.length===topics.length?'Astronauta mirim do universo!':'Cada aventura deixa uma lembrança.'}</h2><p>{completed.length===topics.length?'Todas as descobertas merecem uma grande festa, Tomás!':`Você já guardou ${completed.length} de ${topics.length} figurinhas. Vamos buscar a próxima?`}</p></div><button className="primary" onClick={()=>start(nextMission)}><Rocket/>Explorar</button></div><div className="album-grid">{topics.map((t,i)=>{const done=completed.includes(t.id);return <button key={t.id} className={`album-sticker ${done?'earned-sticker':''}`} onClick={()=>done?visit(t):start(t)}><span className="sticker-id">{String(i+1).padStart(2,'0')}</span>{done?<PlanetBadge id={t.id} size={82}/>:<Lock size={39}/>}<h3>{done?t.name:'Uma nova descoberta'}</h3><span>{done?'★ ★ ★':'Quem será?'}</span></button>})}</div></div>}
 </main><footer><span><Heart size={14}/> Para o Tomás e sua curiosidade sem tamanho.</span><button onClick={()=>{setParent(true);setGate(false)}}><ShieldCheck size={15}/> Área da família</button></footer>
 <AnimatePresence>{!welcomed&&<motion.div className="modal-backdrop welcome-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section className="welcome-card" initial={{scale:.95,y:20}} animate={{scale:1,y:0}} role="dialog" aria-modal="true" aria-label="Bem-vindo, Tomás"><div className="welcome-art"><img className={`suit-${settings.suit}`} src={`${import.meta.env.BASE_URL}art/tomas.webp`} alt="Tomás astronauta acenando"/><span>✦</span><i>✧</i></div><div className="welcome-copy"><span className="eyebrow">Oi, comandante!</span><h1>Tomás,<br/>o universo<br/><em>é seu quintal.</em></h1><p>Planetas, histórias e uma nave cheia de descobertas.</p><div className="suit-picker" aria-label="Cor do traje">{['#52d5c7','#bf95eb','#ffc25f','#98d991'].map((c,i)=><button key={c} style={{background:c}} className={settings.suit===i?'selected':''} onClick={()=>{setSettings(s=>({...s,suit:i}));voice.chime()}} aria-label={`Traje ${['turquesa','violeta','laranja','verde'][i]}`}>{settings.suit===i&&<Check size={20}/>}</button>)}</div><button className="primary" onClick={()=>{setWelcomed(true);void voice.play('welcome')}}><Play fill="currentColor"/>Vamos explorar!</button><span className="welcome-tip"><Volume2 size={17}/> Aperte o play e ouça a Estrelinha.</span></div></motion.section></motion.div>}</AnimatePresence>
 <AnimatePresence>{lesson&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section className="lesson-modal" role="dialog" aria-modal="true" aria-label={`Explorar ${lesson.name}`} initial={{scale:.98,y:30}} animate={{scale:1,y:0}}><header className="lesson-header"><button className="icon-button" onClick={close} aria-label="Voltar à nave"><ArrowLeft/></button><div><small>{mode==='learn'?'Uma descoberta de cada vez':'Hora de brincar'}</small><h2>{lesson.name}</h2></div><button className={`icon-button ${playing?'audio-on':''}`} onClick={()=>voice.repeat()} aria-label="Repetir explicação"><Volume2/></button></header>{mode==='learn'?<><div className="lesson-body"><ChapterScene key={`${lesson.id}-${fact}`} topic={lesson} visual={lesson.facts[fact].visual} reduced={settings.reduced} suit={settings.suit}/><div className="lesson-copy"><span className="eyebrow">Descoberta {fact+1} de 5</span><h1>{lesson.facts[fact].title}</h1><p>{lesson.facts[fact].text}</p><Buddy text="Você pode ouvir de novo ou continuar a viagem." playing={playing}/><div className="story-controls"><button className="secondary icon-button" disabled={fact===0} onClick={()=>setFact(f=>f-1)} aria-label="Descoberta anterior"><ChevronLeft/></button><button className="primary" onClick={()=>{if(fact<4)setFact(f=>f+1);else{setMode('game');voice.stop()}}}>{fact<4?<><Play fill="currentColor"/>Próxima descoberta</>:<><Rocket/>Vamos brincar!</>}</button></div><div className="story-dots">{lesson.facts.map((_,i)=><button key={i} className={fact===i?'active':''} aria-label={`Descoberta ${i+1}`} onClick={()=>setFact(i)}><span/></button>)}</div>{factOnly&&<button className="text-button" onClick={()=>setMode('game')}>Brincar com essa descoberta <Play size={15}/></button>}</div></div></>:<Activities key={lesson.id} topic={lesson} onWin={finish} reduced={settings.reduced}/>}</motion.section></motion.div>}</AnimatePresence>
 <AnimatePresence>{countdown!==null&&<motion.div className="modal-backdrop launch-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="launch-stars"/><motion.div className="launch-rocket" animate={countdown===0?{y:-600}:{y:[0,-10,0]}} transition={{duration:1}}><Rocket size={110}/><span>🔥</span></motion.div><span className="eyebrow">Próxima parada: {mission?.name}</span><motion.strong key={countdown} initial={{scale:.5,opacity:0}} animate={{scale:1,opacity:1}}>{countdown||'Vamos!'}</motion.strong><p>Preparar, sorrir e decolar.</p><button className="secondary" onClick={()=>{setCountdown(null);setMission(null);voice.stop()}}>Voltar à nave</button></motion.div>}</AnimatePresence>
 <AnimatePresence>{reward&&<motion.div className="modal-backdrop reward-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section className="reward-card" role="dialog" aria-modal="true" aria-label="Recompensa" initial={{scale:.8}} animate={{scale:1}}><div className="confetti" aria-hidden="true">{Array.from({length:20},(_,i)=><motion.span key={i} initial={{x:0,y:0,opacity:1}} animate={{x:Math.cos(i)*250,y:Math.sin(i)*250,opacity:0}} transition={{duration:settings.reduced?.01:2,delay:i*.025}}>✦</motion.span>)}</div><div className="reward-stars">★ ★ ★</div><div className="reward-sticker"><PlanetBadge id={reward.id} size={115}/></div><span className="eyebrow">Figurinha conquistada</span><h1>Você foi incrível,<br/><em>Tomás!</em></h1><p>{reward.name} agora faz parte das suas descobertas.</p>{completed.length===topics.length&&<div className="final-medal"><Trophy size={55}/><b>Medalha de Astronauta Mirim</b></div>}<div className="reward-buttons"><button className="primary" onClick={()=>{setReward(null);navigate('missions')}}><Rocket/>Mais aventuras</button><button className="secondary" onClick={()=>{setReward(null);navigate('album')}}><BookOpen/>Ver figurinha</button></div></motion.section></motion.div>}</AnimatePresence>
 {parent&&<div className="modal-backdrop"><section className="parent-modal" role="dialog" aria-modal="true" aria-label="Área da família"><header><div><span className="eyebrow">Um cantinho para os adultos</span><h2>Área da família</h2></div><button className="icon-button" onClick={()=>{setParent(false);setResetConfirm(false);voice.stop()}} aria-label="Fechar ajustes"><X/></button></header>{!gate?<div className="parent-gate"><ShieldCheck size={45}/><p>Para abrir os ajustes, resolva:</p><h1>6 × 3 = ?</h1><div className="answer-options">{[12,18,24].map(n=><button key={n} className="number-tile" onClick={()=>{if(n===18)setGate(true);else setNotice('Peça ajuda a um adulto.')}}>{n}</button>)}</div></div>:<><div className="settings-group"><h3><Headphones/> Voz e som</h3><p>Voz neural brasileira, com áudios incluídos no jogo.</p><label>Volume <input aria-label="Volume" type="range" min="0" max="1" step=".05" value={settings.volume} onChange={e=>setSettings(s=>({...s,volume:+e.target.value}))}/><b>{Math.round(settings.volume*100)}%</b></label><label>Velocidade da narração<select aria-label="Velocidade da narração" value={settings.rate} onChange={e=>setSettings(s=>({...s,rate:+e.target.value}))}><option value=".9">Mais devagar</option><option value="1">Natural</option><option value="1.1">Um pouco mais rápida</option></select></label><div className="setting-toggles"><button onClick={()=>setSettings(s=>({...s,muted:!s.muted}))}>{settings.muted?<VolumeX/>:<Volume2/>}{settings.muted?'Som desligado':'Som ligado'}</button><button onClick={()=>setSettings(s=>({...s,music:!s.music}))}><Music2/>{settings.music?'Música ligada':'Ligar música suave'}</button><button onClick={()=>setSettings(s=>({...s,reduced:!s.reduced}))}><Pause/>{settings.reduced?'Movimento reduzido':'Reduzir movimento'}</button></div></div><div className="settings-group"><h3><Map/> Exploração</h3><button className="secondary" onClick={()=>{setAllOpen(true);setNotice('Todas as aventuras foram liberadas.')}}><Lock/>{allOpen?'Todas as aventuras abertas':'Liberar todas as aventuras'}</button><h3>O que Tomás aprendeu</h3><p>{completed.length?completed.map(id=>topics.find(t=>t.id===id)!.name).join(' · '):'As aventuras concluídas aparecerão aqui.'}</p><p className="small-note">Progresso só nesta sessão. Sem cadastro ou coleta de dados. As ilustrações simplificam tamanhos e distâncias.</p>{resetConfirm?<div className="reset-confirm"><p>Recomeçar as descobertas desta sessão?</p><button className="secondary" onClick={()=>{setCompleted([]);setAllOpen(false);setResetConfirm(false)}}>Sim, recomeçar</button><button className="secondary" onClick={()=>setResetConfirm(false)}>Cancelar</button></div>:<button className="text-button" onClick={()=>setResetConfirm(true)}><Repeat2 size={18}/>Recomeçar progresso</button>}</div></>}</section></div>}
 <AnimatePresence>{notice&&<motion.div className="toast" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{opacity:0}} role="status">{notice}</motion.div>}</AnimatePresence>
 </div></MotionConfig>
}
function HandIcon(){return <span aria-hidden="true" className="hand-icon">✧</span>}

// Máscara de cor: muda apenas os painéis turquesa, preservando pele e cabelo.
function SuitFilters(){return <svg width="0" height="0" aria-hidden="true" style={{position:'absolute'}}><defs>{[110,235,-60].map((h,i)=><filter key={h} id={`suit-filter-${i+1}`} colorInterpolationFilters="sRGB"><feColorMatrix in="SourceGraphic" type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  -3 3 0 0 -0.2" result="mask"/><feComposite in="mask" in2="SourceAlpha" operator="in" result="clipped"/><feColorMatrix in="SourceGraphic" type="hueRotate" values={String(h)} result="hue"/><feComposite in="hue" in2="clipped" operator="in" result="changed"/><feComposite in="SourceGraphic" in2="clipped" operator="out" result="unchanged"/><feMerge><feMergeNode in="unchanged"/><feMergeNode in="changed"/></feMerge></filter>)}</defs></svg>}
